# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-20 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('emob', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('eaadhar', models.IntegerField()),
                ('esalary', models.IntegerField()),
            ],
        ),
    ]
